export default {
  REQUEST_EMPLOYEE_PERSONAL_DATA: 'REQUEST_EMPLOYEE_PERSONAL_DATA',
  RECEIVE_EMPLOYEE_PERSONAL_DATA: 'RECEIVE_EMPLOYEE_PERSONAL_DATA',
  FAILED_EMPLOYEE_PERSONAL_DATA: 'FAILED_EMPLOYEE_PERSONAL_DATA',
};
